services:
  - type: web
    name: flask-student-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: SECRET_KEY
        generateValue: true

